// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVyb9SwNLGHZV3dD0oBkc0mTMmWQIWWJM',
    appId: '1:997994901757:web:66ac86ef6b5d4697920e94',
    messagingSenderId: '997994901757',
    projectId: 'cartoonflix-c49e6',
    authDomain: 'cartoonflix-c49e6.firebaseapp.com',
    storageBucket: 'cartoonflix-c49e6.firebasestorage.app',
    measurementId: 'G-XN2QVQ6KT2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD47Ib_ZYJ19ROSIp9lTXf8ByzHZe_WAL8',
    appId: '1:997994901757:android:1980885c2a38b7c9920e94',
    messagingSenderId: '997994901757',
    projectId: 'cartoonflix-c49e6',
    storageBucket: 'cartoonflix-c49e6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALpYDDq7Oq2sd-07e5DBTfbkiVqEVxUqo',
    appId: '1:997994901757:ios:af33cead65fc49e8920e94',
    messagingSenderId: '997994901757',
    projectId: 'cartoonflix-c49e6',
    storageBucket: 'cartoonflix-c49e6.firebasestorage.app',
    iosBundleId: 'com.example.cartoonMovies',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALpYDDq7Oq2sd-07e5DBTfbkiVqEVxUqo',
    appId: '1:997994901757:ios:af33cead65fc49e8920e94',
    messagingSenderId: '997994901757',
    projectId: 'cartoonflix-c49e6',
    storageBucket: 'cartoonflix-c49e6.firebasestorage.app',
    iosBundleId: 'com.example.cartoonMovies',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVyb9SwNLGHZV3dD0oBkc0mTMmWQIWWJM',
    appId: '1:997994901757:web:931b7b24c94ba502920e94',
    messagingSenderId: '997994901757',
    projectId: 'cartoonflix-c49e6',
    authDomain: 'cartoonflix-c49e6.firebaseapp.com',
    storageBucket: 'cartoonflix-c49e6.firebasestorage.app',
    measurementId: 'G-5E4RB8TLF8',
  );
}
